TASK-354 - Configure CellBase host when creating a new project
opencb/opencga pull request #1955
Opened 2022-04-22 15:41 UTC by juanfeSanahuja

2022-04-22 15:41 UTC, imedina commented
Task linked: [TASK-354 Configure CellBase host when creating a new project](https://app.clickup.com/t/36631768/TASK-354)

2022-05-03 08:08 UTC, pfurio requested changes
Just wondering, why did you make those changes to the docs/data-models files? Is that something automatic your IDE has done? If so, before commiting anything, I would undo/exclude those files for the commit. Unnecessary changes in those doc files has only given us problems and conflicts so far.

2022-05-03 08:08 UTC, pfurio commented on opencga-core/src/main/java/org/opencb/opencga/core/models/project/Project.java
> +            description = FieldConstants.PROJECT_INTERNAL_CELLBASE)
FieldConstants variable should now be called PROJECT_CELLBASE instead of PROJECT_INTERNAL_CELLBASE

2022-05-03 14:04 UTC, juanfeSanahuja commented
The change is done we can merge

2022-05-03 14:11 UTC, pfurio approved these changes

2022-05-03 14:15 UTC, merged