TASK-1100
opencb/opencga pull request #2012
Opened 2022-06-20 19:34 UTC by pfurio

TASK-1100

2022-06-20 19:34 UTC, pfurio commented
Task linked: [TASK-1100 Project configured cellbase being ignored in VariantStorageManager](https://app.clickup.com/t/36631768/TASK-1100)

2022-06-20 20:09 UTC, j-coll requested changes
Take a look to this code:
[VariantStorageManager:989-995](https://github.com/opencb/opencga/blob/v2.3.0/opencga-analysis/src/main/java/org/opencb/opencga/analysis/variant/manager/VariantStorageManager.java#L989-L995)

 The "include" will not include the cellbase object.

2022-06-20 23:52 UTC, imedina requested changes
@pfurio CellBase in Azure is v5 not v4

2022-06-21 10:27 UTC, pfurio commented
Changes made. Please review again when you can @imedina @j-coll

2022-06-21 11:07 UTC, j-coll requested changes

2022-06-21 11:07 UTC, j-coll commented on opencga-core/src/main/java/org/opencb/opencga/core/models/project/ProjectUpdateParams.java
> -    public CellBaseConfiguration getCellbase() {
You need to regenerate the command line. It doesn't compile now

2022-06-21 13:37 UTC, j-coll approved these changes

2022-06-22 07:39 UTC, merged