TASK-1344
opencb/opencga pull request #2049
Opened 2022-07-15 11:54 UTC by juanfeSanahuja

TASK-1344

2022-07-15 11:54 UTC, juanfeSanahuja commented
Task linked: [TASK-1344 Empty smtp server configuration](https://app.clickup.com/t/36631768/TASK-1344)

2022-07-21 13:39 UTC, pfurio requested changes
Please, revert the changes and remove the autogenerated code from the commit/PR. It is really complicated finding the code that has been updated.

2022-07-21 13:45 UTC, pfurio commented on opencga-catalog/src/main/java/org/opencb/opencga/catalog/auth/authentication/AzureADAuthenticationManager.java
> -    private String originId;
Why have you changed the order of those fields? If you are using a plugin that is doing that kind of changes, it would be desirable to disable it.

2022-07-22 10:47 UTC, pfurio approved these changes

2022-07-22 10:58 UTC, merged