TASK-1587
opencb/opencga pull request #2068
Opened 2022-07-28 17:31 UTC by juanfeSanahuja

TASK-1587

2022-07-28 17:31 UTC, juanfeSanahuja commented
Task linked: [TASK-1587 The parameters of the body give an error](https://app.clickup.com/t/36631768/TASK-1587)

2022-07-29 08:20 UTC, j-coll requested changes

2022-07-29 08:20 UTC, j-coll commented on opencga-server/src/main/java/org/opencb/opencga/server/generator/writers/cli/ExecutorsCliRestApiWriter.java
> +                        sb.append("            putNestedIfNotEmpty(beanParams, \"" + label.replaceAll("_body", "") + "\"," + javaCommandOptionsField + ", true);\n ");
This should be `body_` instead of `_body`

2022-07-29 10:25 UTC, pfurio approved these changes

2022-07-29 10:30 UTC, merged