TASK-3991
opencb/opencga pull request #2261
Opened 2023-03-21 16:50 UTC by juanfeSanahuja

TASK-3991 - Release CI/CD workflow should put results of test on xetabase dir on report server

2023-03-21 16:50 UTC, juanfeSanahuja commented
Task linked: [TASK-3991 Release CI/CD workflow should put results of test on xetabase dir on report server](https://app.clickup.com/t/36631768/TASK-3991)

2023-04-04 09:58 UTC, juanrizetta requested changes

2023-04-04 10:06 UTC, juanfeSanahuja commented on opencga-test/src/test/java/org/opencb/opencga/test/manager/LocalDatasetExecutorTest.java
> +   /*     Variant v1 = new Variant().setId(".").setAlternate("T").setChromosome("5")
This is a test only for run in local machine

2023-04-04 10:07 UTC, juanrizetta approved these changes

2023-04-04 10:17 UTC, closed without merging

2023-04-04 10:18 UTC, juanfeSanahuja commented
Wrong target branch