TASK-3885
opencb/opencga pull request #2264
Opened 2023-03-23 23:01 UTC by juanfeSanahuja

TASK-3885 - Script to create hotfix branch

2023-03-23 23:01 UTC, juanfeSanahuja commented
Task linked: [TASK-3885 Script for creating hotfix branch](https://app.clickup.com/t/36631768/TASK-3885)

2023-03-28 09:06 UTC, j-coll requested changes

2023-03-28 09:06 UTC, j-coll commented on misc/new_hotfix_branch.sh
> +cd "$REPO_DIR" || exit 2
REPO_DIR may not be defined. If undefined, this would move to "$HOME"

Use ${REPO_DIR:?} to ensure it's defined

2023-03-28 16:16 UTC, juanfeSanahuja commented on misc/new_hotfix_branch.sh
> +  exit
exit 2 -> Misuse of shell builtins (according to bash documentation)

2023-03-28 16:22 UTC, juanfeSanahuja commented on misc/new_hotfix_branch.sh
> +SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
removed

2023-03-28 16:28 UTC, j-coll commented on misc/new_hotfix_branch.sh
> +  exit
why?

2023-03-29 08:52 UTC, merged