TASK-4163
opencb/opencga pull request #2273
Opened 2023-04-18 11:16 UTC by juanfeSanahuja

TASK-4163 - Modify build workflow to check the same branch name of dependency

2023-04-18 11:16 UTC, juanfeSanahuja commented
Task linked: [TASK-4163 Modify build workflow to check the same branch name of dependency](https://app.clickup.com/t/36631768/TASK-4163)

2023-05-09 17:24 UTC, juanrizetta requested changes

2023-05-09 17:24 UTC, juanrizetta commented on .github/workflows/task.yml
> +    uses: opencb/java-common-libs/.github/workflows/build-java-app-workflow.yml@TASK-4163
Is this correct?

2023-05-15 12:40 UTC, juanrizetta approved these changes

2023-05-18 10:16 UTC, merged