TASK-5055 - ERROR CLI Opencga-enterprise
opencb/opencga pull request #2354
Opened 2023-10-25 15:49 UTC by juanfeSanahuja

TASK-5055 - ERROR CLI Opencga-enterprise

2023-10-26 00:46 UTC, imedina approved these changes

2023-10-27 11:36 UTC, j-coll requested changes

2023-10-27 11:36 UTC, j-coll commented on opencga-app/pom.xml
> +                                    <arg value="${project.basedir}/src/main/resources/usage.yml"/>
This file doesn't exist. It's called "cli-usage.yml"

2023-10-27 11:36 UTC, j-coll commented on opencga-app/src/main/java/org/opencb/opencga/app/cli/config/CliConfiguration.java
> +    public static final String CLI_USAGE_FILENAME = "cli-usage.yml";
Discrepancy between file name. In POM.xml it's expected to be "usage.yml"

2023-10-27 11:36 UTC, j-coll commented on opencga-app/src/main/resources/cli-usage.yml
> +categories:
An small description or commentary header about this new configuration file would be appreciated

2023-11-03 11:20 UTC, j-coll approved these changes

2023-11-03 12:46 UTC, j-coll approved these changes

2023-11-06 09:59 UTC, merged