TASK-5618 - Port Patch 1.10.2 -> 2.0.0
opencb/opencga pull request #2408
Opened 2024-03-06 11:29 UTC by juanfeSanahuja

TASK-5618 - Port Patch 1.10.2 -> 2.0.0

2024-03-06 11:29 UTC, imedina commented
Task linked: [TASK-5618 Port Patch 1.10.2 -> 2.0.0](https://app.clickup.com/t/36631768/TASK-5618)

2024-03-06 11:48 UTC, pfurio approved these changes

2024-03-06 11:54 UTC, j-coll commented
- [TASK-5349](https://app.clickup.com/t/36631768/TASK-5349) #2369 7f39487 - @pfurio
- [TASK-5450](https://app.clickup.com/t/36631768/TASK-5450) #2371 e38f516 - @jtarraga
- [TASK-5404](https://app.clickup.com/t/36631768/TASK-5404) #2372 f6ab5d6 - @juanfeSanahuja
- [TASK-5475](https://app.clickup.com/t/36631768/TASK-5475) #2385 86026da - @juanfeSanahuja
- [TASK-5482](https://app.clickup.com/t/36631768/TASK-5482) #2377 39b05ec - @juanfeSanahuja
- [TASK-5501](https://app.clickup.com/t/36631768/TASK-5501) #2378 cfcf47e - @jtarraga
- [TASK-5452](https://app.clickup.com/t/36631768/TASK-5452) #2374 d51611a - @j-coll
- [TASK-5511](https://app.clickup.com/t/36631768/TASK-5511) #2386 88c589a - @juanfeSanahuja
- [TASK-5580](https://app.clickup.com/t/36631768/TASK-5580) #2388 c361224 - @juanfeSanahuja

2024-03-06 12:01 UTC, j-coll requested changes
All pom.xml files from opencga-storage-hadoop-deps should be removed.

2024-03-07 08:48 UTC, pfurio approved these changes

2024-03-07 10:25 UTC, j-coll approved these changes

2024-03-07 14:18 UTC, merged