TASK-6992 - Error with token in the CLI
opencb/opencga pull request #2509
Opened 2024-09-26 14:59 UTC by juanfeSanahuja

TASK-6992 - Error with token in the CLI

2024-09-26 14:59 UTC, halender commented
Task linked: [TASK-6992 Error with token in the CLI](https://app.clickup.com/t/36631768/TASK-6992)

2024-09-26 15:46 UTC, jtarraga approved these changes

2024-09-27 07:34 UTC, halender approved these changes

2024-09-27 07:34 UTC, pfurio requested changes

2024-09-27 07:34 UTC, pfurio commented on opencga-app/src/main/java/org/opencb/opencga/app/cli/main/processors/CommandProcessor.java
> +        logger.debug("openCGAClient Token: " + openCGAClient.getToken());
Shouldn't we write the log after knowing for sure the opencgaclient has a valid token?

2024-09-27 07:37 UTC, pfurio submitted a review, later dismissed

2024-09-30 13:29 UTC, jtarraga approved these changes

2024-10-01 15:46 UTC, merged