Task 7134 - Re-implement Aggregations Stats for all Catalog Browsers
opencb/opencga pull request #2529
Opened 2024-11-12 10:17 UTC by jtarraga

Re-implement Aggregations Stats for all Catalog Browsers

2024-11-12 10:17 UTC, halender commented
Task linked: [TASK-7134 Re-implement Aggregations Stats for all Catalog Browsers](https://app.clickup.com/t/36631768/TASK-7134)

2024-11-12 11:38 UTC, pfurio requested changes

2024-11-12 11:38 UTC, pfurio commented on opencga-server/src/main/java/org/opencb/opencga/server/rest/CohortWSServer.java
> +            @ApiParam(value = ParamConstants.STUDY_DESCRIPTION)
These fields need to be the same ones we have in the /search and /distinct web service. 'creationYear', 'creationMonth', etc were past fields that we allowed when this was implemented with Solr but not anymore.

2024-11-12 11:38 UTC, pfurio commented on opencga-server/src/main/java/org/opencb/opencga/server/rest/FamilyWSServer.java
> +            @ApiParam(value = ParamConstants.STUDY_DESCRIPTION)
Same here. We should add the fields we currently have in the /search and /distinct web services

2024-11-12 11:38 UTC, pfurio commented on opencga-server/src/main/java/org/opencb/opencga/server/rest/FileWSServer.java
> +            @ApiParam(value = ParamConstants.STUDY_DESCRIPTION)
Same here. We should add the fields we currently have in the /search and /distinct web services

2024-11-12 11:38 UTC, pfurio commented on opencga-server/src/main/java/org/opencb/opencga/server/rest/IndividualWSServer.java
> +            @ApiParam(value = ParamConstants.STUDY_DESCRIPTION)
Same here. We should add the fields we currently have in the /search and /distinct web services

2024-11-12 11:38 UTC, pfurio commented on opencga-server/src/main/java/org/opencb/opencga/server/rest/JobWSServer.java
> +            @ApiParam(value = ParamConstants.STUDY_DESCRIPTION) @QueryParam(ParamConstants.STUDY_PARAM) String studyStr,
Same here. We should add the fields we currently have in the /search and /distinct web services

2024-11-12 11:38 UTC, pfurio commented on opencga-server/src/main/java/org/opencb/opencga/server/rest/PanelWSServer.java
> +            @ApiParam(value = ParamConstants.STUDY_DESCRIPTION) @QueryParam(ParamConstants.STUDY_PARAM) String studyStr,
Same here. We should add the fields we currently have in the /search and /distinct web services

2024-11-12 11:38 UTC, pfurio commented on opencga-server/src/main/java/org/opencb/opencga/server/rest/SampleWSServer.java
> +            @ApiParam(value = ParamConstants.STUDY_DESCRIPTION) @QueryParam(ParamConstants.STUDY_PARAM) String studyStr,
Same here. We should add the fields we currently have in the /search and /distinct web services

2024-11-13 13:54 UTC, pfurio submitted a review, later dismissed

2025-01-23 08:21 UTC, pfurio approved these changes

2025-02-03 10:55 UTC, pfurio submitted a review, later dismissed

2025-02-05 10:17 UTC, pfurio approved these changes

2025-02-10 11:54 UTC, juanfeSanahuja approved these changes

2025-02-10 14:57 UTC, merged