TASK-6442 - Add Resources Management functionality
opencb/opencga pull request #2535
Opened 2024-12-10 11:37 UTC by pfurio

2024-12-10 14:01 UTC, j-coll requested changes

2024-12-10 15:05 UTC, pfurio commented on opencga-catalog/src/main/java/org/opencb/opencga/catalog/managers/FileManager.java
> +        return path.startsWith("RESOURCES/") || path.startsWith("resources/");
It should be in upper case. However, we should be smart enough to identify if a user is using it in lower case

2024-12-19 10:03 UTC, jtarraga commented on opencga-catalog/src/test/java/org/opencb/opencga/catalog/managers/ResourceManagerTest.java
> +$ cat resources-3.3.0-SNAPSHOT.json | jq
This PR wasn’t ready yet; it was approved prematurely. Please review it now.

2024-12-19 10:03 UTC, jtarraga commented on opencga-catalog/src/test/resources/configuration-test.yml
> +  resourceUrl: "http://resources.opencb.org/opencb/opencga/analysis/resources-test/"
This PR wasn’t ready yet; it was approved prematurely. Please review it now.

2024-12-19 10:03 UTC, jtarraga commented on opencga-core/src/main/java/org/opencb/opencga/core/models/resource/AnalysisResourceList.java
> +    private String analysisId;
This PR wasn’t ready yet; it was approved prematurely. Please review it now.

2024-12-19 10:04 UTC, jtarraga commented on opencga-core/src/main/java/org/opencb/opencga/core/models/resource/AnalysisResource.java
> +public class AnalysisResource {
This PR wasn’t ready yet; it was approved prematurely. Please review it now.

2024-12-19 10:04 UTC, jtarraga commented on opencga-catalog/src/main/java/org/opencb/opencga/catalog/utils/ResourceManager.java
> +            isFetching = true;
This PR wasn’t ready yet; it was approved prematurely. Please review it now.

2024-12-19 10:04 UTC, jtarraga commented on opencga-catalog/src/main/java/org/opencb/opencga/catalog/utils/ResourceManager.java
> +    private boolean isFetching = false;
This PR wasn’t ready yet; it was approved prematurely. Please review it now.

2025-01-21 17:28 UTC, j-coll reviewed
Review WIP

2025-01-21 17:28 UTC, j-coll commented on opencga-core/src/main/java/org/opencb/opencga/core/api/FieldConstants.java
> +    public static final String FILE_RESOURCE = "Indicates the file is treated as a resource.";
Isn't this param almost identical to the ParamConstant "FILE_RESOURCE_DESCRIPTION" ? Why?

2025-01-21 17:28 UTC, j-coll commented on opencga-app/src/main/java/org/opencb/opencga/app/migrations/v4/v4_0_0/catalog/ResourcesMigration.java
> +        queryMongo(OrganizationMongoDBAdaptorFactory.STUDY_COLLECTION, new Document(),
No migration test?

2025-01-21 17:28 UTC, j-coll commented on opencga-catalog/src/main/java/org/opencb/opencga/catalog/db/mongodb/StudyMongoDBAdaptor.java
> +            URI studyUri = ioManager.getStudyUri(organization, Long.toString(project.getUid()), Long.toString(study.getUid()));
Understand...
I'd recommend creating a ticket to keep track of this, something like:
"Expose transactions API and remove IOManager from DBAdaptors"
The exposed transactions API should be only for internal use from the Managers, never from outside

2025-01-21 17:28 UTC, j-coll commented on opencga-catalog/src/main/java/org/opencb/opencga/catalog/managers/FileManager.java
> +            boolean isResource = createParams.getResource() != null && createParams.getResource();
works the same and slightly shorter if you do `createParams.getResource() == Boolean.TRUE`

2025-01-22 14:36 UTC, j-coll commented on opencga-catalog/src/test/resources/configuration-test.yml
> +  resourceUrl: "http://resources.opencb.org/opencb/opencga/analysis/resources-test/"
Again, is "resources-test/" the actual final value for this? or just a temporary thing?

2025-01-22 15:05 UTC, j-coll requested changes

2025-01-22 15:05 UTC, j-coll commented on opencga-catalog/src/main/java/org/opencb/opencga/catalog/managers/FileManager.java
> +            throw new CatalogException("Linked files cannot be stored in the RESOURCES folder.");
a Resource file can be uploaded but not linked? Why?

2025-02-17 11:34 UTC, pfurio commented on opencga-catalog/src/main/java/org/opencb/opencga/catalog/managers/FileManager.java
> +            throw new CatalogException("Linked files cannot be stored in the RESOURCES folder.");
Because RESOURCE files are not external by definition.

2025-02-17 12:48 UTC, jtarraga commented on opencga-catalog/src/main/java/org/opencb/opencga/catalog/utils/ResourceManager.java
> +            this.configuration = Configuration.load(new FileInputStream(openCgaHome.resolve(CONF_DIRNAME)
Updated to close the FileInputStream

2025-02-18 11:30 UTC, juanfeSanahuja approved these changes

2025-02-19 00:41 UTC, imedina submitted a review, later dismissed

2025-02-19 16:37 UTC, juanfeSanahuja submitted a review, later dismissed

2025-02-24 13:12 UTC, juanfeSanahuja submitted a review, later dismissed

2025-02-25 09:30 UTC, jtarraga submitted a review, later dismissed

2025-02-25 09:37 UTC, juanfeSanahuja submitted a review, later dismissed

2025-02-25 09:37 UTC, jtarraga approved these changes

2025-02-25 12:46 UTC, jtarraga approved these changes

2025-02-25 15:53 UTC, jtarraga approved these changes

2025-02-25 20:10 UTC, merged